spring:
  application:
    name: hello-spring-cloud-service-admin
  #redis数据库索引默认为0
  redis:
    database: 0
    host: 192.165.0.19
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/